config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get "/errors/not_found", as: "error404"
  resources :categories
  resources :comments
  resources :posts
  root "posts#index"
  get "*any", via: :all, to: "errors#not_found"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  include CommentConcern
  default_scope {order(:name)}
  has_and_belongs_to_many :posts
  has_many :comments, as: :commentable, dependent: :destroy
  validates :name, presence: true
  paginates_per 10
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Base
  belongs_to :commentable, polymorphic: true
  default_scope {order("created_at ASC")}
  validates :author, :content, presence: true
  validate :comment_author, on: :create

  def comment_author
    errors.add(:author, "need two words with capital letters") unless
    author.present? and author.split.size == 2 and author.split.map{|word| true if word[0].capitalize == word[0]}.reduce(:&)
  end



end

app/models/concerns/base.rb
module Base
  extend ActiveSupport::Concern

  def date
    self.created_at.strftime("%d-%m-%Y %H-%M")
  end

end

app/models/concerns/comment_concern.rb
module CommentConcern
  extend ActiveSupport::Concern

  def comments_count
    self.comments.count
  end

end

app/models/post.rb
class Post < ApplicationRecord
  include Base
  include CommentConcern
  default_scope {order(created_at: :desc)}
  has_and_belongs_to_many :categories
  has_many :comments, as: :commentable, dependent: :destroy
  has_attached_file :file,    styles: { medium: "500x500>", thumb: "250x250>" }
  validates_attachment_content_type :file, 
  content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  validates_attachment_size :file, :in => 0.megabytes..2.megabytes
  validates :name, :content, presence: true
  paginates_per 25


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show]

  def index
    @categories = Category.page params[:page]
  end

  def show
  end

  private

  def set_category
    @category = Category.find(params[:id]) or redirect_to error404_path
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.save
    respond_to do |format|
      format.js {} 
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :content, :commentable_type, :commentable_id)
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    respond_to do |format|
      format.html { render status: 404 }
    end
  rescue ActionController::UnknownFormat
    render status: 404, text: "nope"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show]

  def index
    @posts = Post.page params[:page]
  end

  def show
  end


  private
    def set_post
      @post = Post.find_by(id: params[:id]) or redirect_to error404_path
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def root_active
    "active" if current_page?(root_path)
  end

  def full_title(page_title)
    base_title = "The Bootstrap Blog"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def page_active(name)
    "active" if controller_name == name and !current_page?(root_path)
  end

  def auth
    if current_user
      link_to "Sign Out", destroy_user_session_path, class: "nav-link", method: :delete
    else
      link_to "Sign In", new_user_session_path, class: "nav-link"
    end
  end

  def post_categories post
    "Categories: #{post.categories.map{|category| link_to category.name, category}.join(',')}".html_safe if post.categories.any?
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/categories/_item.html.haml
.blog-post
  %h2.blog-post-title 
    = link_to category.name, category
  %p
  .category-description
    = category.description

app/views/categories/_posts_list.html.haml
%h2 Posts of Category
%ul
  - category.posts.each do |post|
    %li
      = link_to post.name, post_path(post)

app/views/categories/index.html.haml
- content_for :title, 'Categories'
.categories-list
  - @categories.each do |category|
    = render partial: "item", locals: {category: category}
  = paginate @categories, theme: 'twitter-bootstrap-4'    

app/views/categories/show.html.haml
- content_for :title, @category.name
= render partial: "item", locals: {category: @category}
= render partial: "posts_list", locals: {category: @category} if @category.comments.any?
= render partial: "comments/list", locals: {object: @category}

app/views/comments/_form.html.haml
.error_messages
= simple_form_for(object.comments.new, html: { class: 'form-horizontal'}, remote: true) do |f|
  = f.input :commentable_type, :as => :hidden
  = f.input :commentable_id, :as => :hidden
  = f.input :author
  = f.input :content
  = f.button :submit

app/views/comments/_item.html.haml
%a{:name => "comments"}
%li.media
  = image_tag "defaultuser.png", class: "d-flex mr-3"
  .media-body
    %h5.mt-0.mb-1 
      = "#{comment.author} (#{comment.date})"
    = comment.content

app/views/comments/_list.html.haml
%ul.list-unstyled#comments-list
  - object.comments.each do |comment|
    = render partial: "comments/item", locals: {comment: comment}
= render partial: "comments/form", locals: {object: object}

app/views/comments/create.js.erb
<% if @comment.errors.any? %>
$('.error_messages').html(' <%= escape_javascript(render partial: "shared/error_messages", locals: {object: @comment}) %>');
<% else %>
$('.error_messages').html('');
$('#comments-list').append('<%= escape_javascript(render partial: "comments/item", locals: {comment: @comment}) unless @comment.errors.any? %>');
$('#comment_author').val('');
$('#comment_content').val('');
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title
      = full_title(yield(:title))
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "shared/header"
    .container
      .row
        .col-sm-8.blog-main
          = yield
        / /.blog-main
        .col-sm-3.offset-sm-1.blog-sidebar
          = render "shared/sidebar"
        / /.blog-sidebar
      / /.row
    / /.container
    = render "shared/footer"
    

app/views/posts/_item.html.haml
.blog-post
  %h2.blog-post-title 
    = link_to post.name, post
  %p.blog-post-meta
    = post.date
  %p.blog-post-meta
    = post_categories(post)
  %p
    = image_tag post.file.url(:medium) if post.file.present?
  .post-content
    = post.content
  = link_to "Comments(#{post.comments_count})", post_path(post,anchor: "comments") if action_name == 'index'

app/views/posts/index.html.haml
- content_for :title, "Posts"
.posts-list
  - @posts.each do |post|
    = render partial: "item", locals: {post: post}
  = paginate @posts, theme: 'twitter-bootstrap-4'

app/views/posts/show.html.haml
- content_for :title, @post.name
= render partial: "item", locals: {post: @post}
= render partial: "comments/list", locals: {object: @post}

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  .alert.alert-danger
    This form has #{pluralize(object.errors.count, 'problem')}
  %ul
    - object.errors.full_messages.each do |msg|
      %li.alert.alert-danger= msg

app/views/shared/_footer.html.haml
%footer.blog-footer
  %p
    Blog template built for
    %a{:href => "https://getbootstrap.com"} Bootstrap
    by
    = succeed "." do
      %a{:href => "https://twitter.com/mdo"} @mdo
 

app/views/shared/_header.html.haml
.blog-masthead
  .container
    %nav.nav
      = link_to "Home",root_path, class: "nav-link #{root_active}"
      = link_to "Categories", categories_path, class: "nav-link #{page_active('categories')}"
      = link_to "Posts", posts_path, class: "nav-link #{page_active('posts')}"
      = link_to "Admin Panel", rails_admin_path, class: "nav-link" if current_user
      = auth
.blog-header
  .container
    %h1.blog-title The Bootstrap Blog
    %p.lead.blog-description An example blog template built with Bootstrap.

app/views/shared/_sidebar.html.haml
.sidebar-module
  %h4 Categories
  %ol.list-unstyled
    - Category.all.each do |category|
      %li
        = link_to category.name, category